export const projects = [
  {
    img: '/assets/img/budget.png',
    link: 'https://finance-orcin-tau.vercel.app/',
    name: 'About.projectName1',
    year: '2025',
    mount: 'About.projectMount1',
    info: 'About.projectInfo1',
  },
  {
    img: '/assets/img/Elegant.jpg',
    link: 'https://ecomerce-one-rho.vercel.app/',
    year: '2025',
    name: 'About.projectName2',
    mount: 'About.projectMount2',
    info: 'About.projectInfo2',
  },
  {
    img: '/assets/img/audioPlay.png',
    link: 'https://giorgi175.github.io/Re_giorgi/?authuser=0',
    year: '2024',
    name: 'About.projectName3',
    mount: 'About.projectMount3',
    info: 'About.projectInfo3',
  },
  {
    img: '/assets/img/movie.png',
    link: 'https://giorgi175.github.io/Tailwind_markup/',
    year: '2024',
    name: 'About.projectName4',
    mount: 'About.projectMount4',
    info: 'About.projectInfo4',
  },
  {
    img: '/assets/img/SimplePortfolio.png',
    link: 'https://react-hmwrk2.vercel.app/',
    year: '2024',
    name: 'About.projectName5',
    mount: 'About.projectMount5',
    info: 'About.projectInfo5',
  },
  {
    img: '/assets/img/CountryApi.png',
    link: 'https://dinamyc-router.vercel.app/',
    year: '2024',
    name: 'About.projectName6',
    mount: 'About.projectMount6',
    info: 'About.projectInfo6',
  },
  {
    img: '/assets/img/RickAndMortApi.png',
    link: 'https://debounce-nu.vercel.app/',
    year: '2024',
    name: 'About.projectName7',
    mount: 'About.projectMount7',
    info: 'About.projectInfo7',
  },
  {
    img: '/assets/img/bank.png',
    link: 'https://challenge-2-starter-one.vercel.app/',
    year: '2024',
    name: 'About.projectName8',
    mount: 'About.projectMount8',
    info: 'About.projectInfo8',
  },
  {
    img: '/assets/img/weatherApi.png',
    link: 'https://giorgi175.github.io/WeatherAPI/',
    year: '2024',
    name: 'About.projectName9',
    mount: 'About.projectMount9',
    info: 'About.projectInfo9',
  },
  {
    img: '/assets/img/gitHubApi.png',
    link: 'https://giorgi175.github.io/githubAPI/',
    year: '2024',
    name: 'About.projectName10',
    mount: 'About.projectMount10',
    info: 'About.projectInfo10',
  },
  {
    img: '/assets/img/FAQ.png',
    link: 'https://giorgi175.github.io/FAQ/',
    year: '2024',
    name: 'About.projectName11',
    mount: 'About.projectMount11',
    info: 'About.projectInfo11',
  },
  {
    img: '/assets/img/rockStrar.png',
    link: 'https://giorgi175.github.io/RockstarLauncherResponsive/',
    year: '2024',
    name: 'About.projectName12',
    mount: 'About.projectMount12',
    info: 'About.projectInfo12',
  },
  {
    img: '/assets/img/keyBoard.png',
    link: 'https://giorgi175.github.io/keyboard/',
    year: '2024',
    name: 'About.projectName13',
    mount: 'About.projectMount13',
    info: 'About.projectInfo13',
  },
  {
    img: '/assets/img/grid.png',
    link: 'https://giorgi175.github.io/responsieCard2/',
    year: '2024',
    name: 'About.projectName14',
    mount: 'About.projectMount14',
    info: 'About.projectInfo14',
  },
  {
    img: '/assets/img/sunnyside.png',
    link: 'https://giorgi175.github.io/togglenavbar/#',
    year: '2024',
    name: 'About.projectName15',
    mount: 'About.projectMount15',
    info: 'About.projectInfo15',
  },
];
