export const projects = [
  {
    img: '/assets/img/budget.png',
    link: 'https://finance-orcin-tau.vercel.app/',
    name: 'Finance web',
    year: '2025',
    mount: 'MAY',
    info: 'სწავლის  ბოლოს ფავიყავით ჯგუფედაბ და ავაწყეთ პორექტები ასე მივიღეთ პირველი ერთად მუშაობის გამოცდიელბა ეს პორექი არის ჩემი პირველი ჯგუფური ნამუშევრის შედეგი გამოვიყენეთ expressJS და NextLS ',
  },
  {
    img: '/assets/img/Elegant.jpg',
    link: 'https://ecomerce-one-rho.vercel.app/',
    name: 'Elegant web',
    year: '2025',
    mount: 'MAY',
    info: 'სწავლის  ბოლოს ფავიყავით ჯგუფედაბ და ავაწყეთ პორექტები ასე მივიღეთ პირველი ერთად მუშაობის გამოცდიელბა ეს პორექი არის ჩემი პირველი ჯგუფური ნამუშევრის შედეგი გამოვიყენეთ expressJS და NextLS ',
  },
  {
    img: '/assets/img/audioPlay.png',
    link: 'https://giorgi175.github.io/Re_giorgi/?authuser=0',
    name: 'audioPlay web',
    year: '2024',
    mount: 'MAY',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/movie.png',
    link: 'https://giorgi175.github.io/Tailwind_markup/',
    name: 'Simple Movies web',
    year: '2024',
    mount: 'SEP',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/SimplePortfolio.png',
    link: 'https://react-hmwrk2.vercel.app/',
    name: 'Simple Portfolio web',
    year: '2024',
    mount: 'AUG',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/CountryApi.png',
    link: 'https://dinamyc-router.vercel.app/',
    name: 'Country API web',
    year: '2024',
    mount: 'AUG',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/RickAndMortApi.png',
    link: 'https://debounce-nu.vercel.app/',
    name: 'Rick And Mort API web',
    year: '2024',
    mount: 'JUN',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/bank.png',
    link: 'https://challenge-2-starter-one.vercel.app/',
    name: 'bank web',
    year: '2024',
    mount: 'MAY',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/weatherApi.png',
    link: 'https://giorgi175.github.io/WeatherAPI/',
    name: 'Weater API web',
    year: '2024',
    mount: 'APR',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/gitHubApi.png',
    link: 'https://giorgi175.github.io/githubAPI/',
    name: 'GitHub API web',
    year: '2024',
    mount: 'APR',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/FAQ.png',
    link: 'https://giorgi175.github.io/FAQ/',
    name: 'mini FAQ',
    year: '2024',
    mount: 'MAR',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/rockStrar.png',
    link: 'https://giorgi175.github.io/RockstarLauncherResponsive/',
    name: 'RockStrar web',
    year: '2024',
    mount: 'feb',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/keyBoard.png',
    link: 'https://giorgi175.github.io/keyboard/',
    name: 'keyBoard web',
    year: '2024',
    mount: 'feb',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/grid.png',
    link: 'https://giorgi175.github.io/responsieCard2/',
    name: ' grid',
    year: '2024',
    mount: 'feb',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
  {
    img: '/assets/img/grid.png',
    link: 'https://giorgi175.github.io/togglenavbar/#',
    name: ' წფ',
    year: '2024',
    mount: 'feb',
    info: 'პირველი ეტაპის ბოლოს ავაწყეთ მხლოდ ჯავასკრიპტით',
  },
];
